from pydantic import BaseModel, Field
from typing import List, Optional, Any
from datetime import date, datetime

class RawHealthData(BaseModel):
    user_id: str
    data_source: str = Field(description="E.g., 'apple_health_xml' or 'healthkit_json'")
    payload: Any = Field(description="Raw payload containing XML (str) or JSON (dict) data")

class DailyMetrics(BaseModel):
    user_id: str
    date: date
    rhr_avg: Optional[float] = Field(None, description="Average Resting Heart Rate")
    hrv_rmssd: Optional[float] = Field(None, description="Heart Rate Variability (RMSSD)")
    sleep_duration_hrs: Optional[float] = Field(None, description="Total Sleep Time in hours")
    respiratory_rate_avg: Optional[float] = Field(None, description="Average Respiratory Rate")

class AnomalyReport(BaseModel):
    user_id: str
    date: date
    is_stress_event: bool
    score: float = Field(description="Anomaly score from the pre-trained model")

class JournalEntry(BaseModel):
    id: Optional[str] = None
    user_id: str
    timestamp: datetime
    mood_score: int = Field(ge=1, le=10, description="1-10 slider score")
    text_content: str
    
class AgentResponse(BaseModel):
    user_id: str
    date: date
    prompts: List[str] = Field(description="2-3 contextual journal prompts generated by the Agent")
    daily_summary: str = Field(description="A paragraph linking today's physiology and mood")
